// ------------------------------------------------------------------------------
//  <autogenerated>
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyTitle("Castle.Services.Logging.SerilogIntegration 3.3.3 for .NETFramework v4.5")]
[assembly: System.Reflection.AssemblyDescription("Castle.Services.Logging.SerilogIntegration 3.3.3 for .NETFramework v4.5")]
[assembly: System.Reflection.AssemblyProduct("Castle.Services.Logging.SerilogIntegration")]
[assembly: System.Reflection.AssemblyVersion("3.3.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("3.3.3.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("3.3.3.0")]
